### Tópicos: Importação do NumPy, Array, Estruturas Unidimensionais, Estruturas Bidimensionais, Shape (saber/ver o tamanho do array), Ndim (dimensões do array), Método MAX, Método Arrange (de 0 ao último exclusivo), Método Linspace (de 0 ao último ñ exclusivo), Estruturas de Matrizes, Numpy.zeros (Preenche com 0), Numpy.ones (Preenche com 1), Numpy.eye (Cria Matriz Identitiy), Numpy.diag (Define números das diagonais), Numpy.empty (Cria Matriz vazia), Numpy.tile (Repete o Arays em linhas ou colunas) 

## Numpy - Biblioteca matemática, mais utilizada com Álgebra Linear. Vetores e Matrizes.

# Descomplicando Matrizes:

Mn x n = 

Linha x Coluna = 

5, 10 = 

5 linhas por 10 Colunas
_______________________________

Matriz Linha = [1 4 5 -9 n...] = 1 Linha, N colunas
_______________________________

Matriz Coluna [1
               2
               7
               n] = 1 Coluna, N Linhas
_______________________________

Matriz Unitária [89] = 1 Linha, 1 Coluna (1x1)
_______________________________

Matriz Retangular (Linha diferente de Coluna)= m <> n = 3 > 2
_______________________________

Matriz Quadrada (Linha igual Coluna)= m = n = 3 = 3
________________________________

M. Quadrada - Diagonal Principal = Diagonal que Vai

M. Quadrada - Diagonal Secundária = Diagonal que Vem
________________________________

Martrizes Quadradas pode se chamar = Matriz de Ordem 3, Matriz de Ordem 3, Matriz de Ordem 7, etc. (Linha igual Coluna)

O Número da Diagonal será sempre a ordem da matriz (em matriz quadrada)
_________________________________

Matriz Tringular Inferior = Valores em baixo da diagonal

Matriz Tringular Superior = Valores em cima da diagonal
__________________________________

Matriz Diagonal = Todos os valores são nulos menos os da diagonal
__________________________________

Matriz Identidade = Diagonal principal toda igual a 1
__________________________________

Matriz Simétrica = Os elementos estão posicionalmente iguais em ambos os lados

# Operações com Matrizes

Soma & Subtração:
As matrizes precisam ser de mesma dimensão para Soma e Subtração
Soma ou subtrai a mesma posição com a mesma posição da outra matriz = matriz resultado
_____________________________________________

Multiplicação Escalar = Todos os índices pelo mesmo número

Ex: 5 x cada posição na matriz = matriz resultado com o resultado na mesma posição anterior 
____________________________________________

Produto entre Matrizes

Regra Principal  = Só é posível quando Linhas de uma matriz é igual a Colunas da outra matriz

Regra Secundária = Não é comutativo AxB é diferente de BxA

Matriz 1 = 3 x 2 (2 Colunas)
Matriz 2 = 2 x 3 (2 Linhas)

Tamanho Matriz Resultado = O que sobra = Matriz Resultado será 3 x 3 (3 linhas e 3 colunas)
 
Multiplicar = Multiplica posição das linhas por colunas (Image 19 Edit -  A Biblioteca NumPy.png)
____________________________________________

Divisão entre matrizes

Divisão entre A x B (Matriz 1 / Matriz 2) é igual Multilplicação da Matriz 1 pela Matriz 2 inversa (Matriz 1 * Matriz 2 inversa)
_______________________________________

Matriz Transposta = Escrever linhas como colunas = O que é linha vira coluna e vise e versa
________________________________________

Exercícios:

Simetrica [3 5 7]
          [2 4 6]
          [1 3 5]
           
Transposta [3 2 1]
           [5 4 6]
           [7 6 5]
_________________________________________            

In [2]:
#Importação do NumPy
import numpy as np

Estruturas Unidimensionais

In [3]:
a1 = np.array(['Spark','Hadoop','Python','R'])

In [4]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

# Arrays podem ter listas de tipos diferentes

Estruturas Bidimensionais

In [5]:
# Forma errada: (['Altura','Largura','Profundidade'],[42, 78, 10]) 

# Forma certa: ([['Altura','Largura','Profundidade'],[42, 78, 10]])

In [6]:
a2 = np.array([['Altura','Largura','Profundidade'],[42, 78, 10]]) # Usar dois blocos de paranteses + o pareteses do NumPy

In [7]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [8]:
a3 = np.array([[10,20,30],[40,50,60],[40,50,60]])

In [9]:
a3 # Assim começamos a montar uma matriz

array([[10, 20, 30],
       [40, 50, 60],
       [40, 50, 60]])

In [10]:
# Para saber/ver o tamanho do array
print(a1.shape)
print(a2.shape)
print(a3.shape)

(4,)
(2, 3)
(3, 3)


In [11]:
#Dimensoes do Array
a1.ndim

1

In [12]:
a2.ndim

2

In [13]:
a3.ndim

2

Nota: Ausência ou presença de parênteses: Realizar uma analogia com Características e Ações. 

-> O uso de parênteses reflete uma AÇÃO. 

-> A ausência de parenteses, reflete uma CARACTERÍSTICA.

In [14]:
#O método max() não funciona em arrays de tipo heterogeneo
a3.max()

60

In [15]:
# Atributo
print(a2.ndim)
print(a3.ndim)

2
2


# Método Arrange

In [16]:
array = np.arange(30) #Começa de 0 e o último é exclusivo 
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
# Usando start/end - de 0 a 100 de 10 em 10
array = np.arange(0, 100, 10)

In [18]:
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

<h2>Criando estruturas de dados com linspace</h2>

In [19]:
# Fique atento: A diferença do linspace para o arange é que no arange o último argumento é o incremento,
# e no linspace o último arqgumento é o número de elementos do vetor (aleatorio)
matriz = np.linspace(0,10,20)
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
matriz = np.linspace(0,10,5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
matriz = np.linspace(0,5,5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

# Estruturas de Matrizes

In [22]:
#numpy.zeros
matriz = np.zeros((10, 10)) # 10 linhas, 10 colulas | # Predenche com (0) zeros. 
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
#numpy.ones
matriz = np.ones((2, 3)) # Predenche com (1) uns
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Numpy.eye - Produz uma matriz do tipo Identitiy
matriz = np.eye(10) # Diagonal de (1)
matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
# numpy.diag produz o mesmo resultado, porem podemos definir os numeros das diagonais

matriz = np.diag((2,4,6,8,10,12,14,16,18,20))
matriz

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [46]:
# numpy.empty produz uma matriz vazia
# 10 linhas, 5 colulas

matriz = np.empty([10, 3])
print(matriz)

[[1.24424222e-311 9.58487353e-322 0.00000000e+000]
 [0.00000000e+000 5.55603410e+180 5.02034658e+175]
 [9.51186062e+169 3.37859702e-057 1.05225943e-046]
 [2.93117483e-057 1.47763641e+248 1.16096346e-028]
 [7.69165785e+218 1.35617292e+248 7.83892484e-067]
 [1.29260943e+161 1.46069326e+185 5.99294154e-066]
 [4.25759014e-096 6.32299154e+233 6.48224638e+170]
 [5.22411352e+257 5.74020278e+180 8.37174974e-144]
 [1.41529402e+161 9.16651763e-072 4.74020289e+097]
 [1.74687542e-076 3.08264916e+126 2.43895101e-154]]


<h3>numpy.tile</h3>

In [60]:
# Multiplicação de Arays 
# Repete o Arays nas linhas ou colunas

np.tile(np.array([[1, 2], [3, 4], [5, 6]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [61]:
# Primeiro elemento é o numero de vezes do array na vertical.
# Segundo elemento é o numero de vezes do array na horizontal.

np.tile(np.array([[1, 2], [3, 4], [5, 6]]), (3,6)) 

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])