### Tópicos: Matrizes NumPy, matriz só pode ter duas dimensões, 2 Colchetes = 2 Dimensões, 3 Colchetes = 3 Dimensões ou cubo,  Soma de Array, Subtração de Array, Multiplicação de Array, Inversa (np.linalg inverte a matriz, junto com inv), Transposta (Troca as linhas por colunas)

# Matrizes NumPy

In [4]:
#Matrizes são objetos ESTRITAMENTE bidimensionais, o que torna mais fácil as operações aritméticas
#Matriz só pode ter duas dimensões

In [1]:
import numpy as np

In [2]:
A = np.matrix([[1, 2], [3, 4]])

B = np.matrix([[5, 3], [8, 7]])

Z = np.array([[[2,6], [8,4]], [[2,6], [8,4]], [[2,6], [8,4]]])

#ou

#Z = np.array([
#              [[2,6], [8,4]],
#              [[2,6], [8,4]], 
#              [[2,6], [8,4]]
#            ])

Y = np.array([2,6,8,4])

In [3]:
#Matriz só pode ter duas dimensões, do contrário dá erro

Z = np.matrix([
    [[2,6], [8,4]] , 
    [[2,6], [8,4]],
    [[2,6], [8,4]]
])

ValueError: matrix must be 2-dimensional

In [4]:
print(type(A))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [5]:
print(type(Z))

<class 'numpy.ndarray'>


In [40]:
print(type(Y))

<class 'numpy.ndarray'>


In [41]:
print(A) # 2 Colchetes = 2 Dimensões 

[[1 2]
 [3 4]]


In [42]:
print(Z) # 3 Colchetes = 3 Dimensões ou cubo 

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [43]:
print(Y)

[2 6 8 4]


In [44]:
Z.shape

(3, 2, 2)

In [45]:
Y.shape

(4,)

## Soma

In [26]:
# Soma os elementos em suas posições 
print(A)
print(B)
print('----')
print(A + B)

[[1 2]
 [3 4]]
[[5 3]
 [8 7]]
----
[[ 6  5]
 [11 11]]


In [27]:
# Adiciona 3 a cada elemento em sua posição
print(B)
print('----')
print(B + 3) 

[[5 3]
 [8 7]]
----
[[ 8  6]
 [11 10]]


## Subtração

In [28]:
print(A)
print(B)
print('----')
print(A-B)

[[1 2]
 [3 4]]
[[5 3]
 [8 7]]
----
[[-4 -1]
 [-5 -3]]


## Multiplicação

In [46]:
A = np.matrix([[1, 2], [3, 4]])

print(A)

[[1 2]
 [3 4]]


In [48]:
#Arrumação em "cruz"

print (A * A)

[[ 7 10]
 [15 22]]


In [49]:
#Multiplicação Indice a Indice
# Multiplica um elemento por ele mesmo na mesma posição

print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


## Inversa

In [51]:
# Pacote np.linalg é pra inversão de matriz, junto com o pacote inv 

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [55]:
# Pacote numpy.linalg é pra inversão de matriz, junto com o pacote inv 

from numpy.linalg import inv

In [56]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Transposta

In [58]:
print(A.T) # Troca as linhas por colunas 

[[1 3]
 [2 4]]
