### Tópicos: Transposta (troca as linhas por colunas), Broadcasting, Convertendo Matrizes em Arrays, Ravel (transforma uma matriz em um vetor - array)), Operadores Lógicos, Random, Reshaping, Reshape (muda tamanho ou muda array para matriz), Ordenando Array (SORT(AXIS = 1) e SORT(AXIS = 0))

# Transposição e Reshaping de Arrays

In [1]:
import numpy as np

In [2]:
A = np.array([[10, 20, 30], [40, 50, 60]])

In [3]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
A.T        # Transposta = Função direto na matriz

array([[10, 40],
       [20, 50],
       [30, 60]])

In [6]:
np.transpose(A)   # Transposta = Função direto na biblioteca

array([[10, 40],
       [20, 50],
       [30, 60]])

## Broadcasting

In [9]:
B = np.array([[100, 200, 300]]) # Array de uma linha

In [11]:
B.T       # Array transposto para uma coluna

array([[100],
       [200],
       [300]])

In [13]:
B.T + B # Soma cada elemento da coluna com um elemento da linha por vez

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

## Convertendo Matrizes em Arrays

In [14]:
A = np.array([np.arange(10,60,10), np.arange(100,150,10)])

In [15]:
A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [16]:
A.shape

(2, 5)

In [20]:
# Esse comando transforma uma matriz em um vetor(array)
A.ravel() 

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [22]:
# Esse comando transforma uma matriz em um vetor(array) transposto
A.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

## Operadores Lógicos

In [27]:
array = np.random.randint(1, 10, size = (4,4))

In [28]:
array

array([[4, 1, 4, 1],
       [7, 2, 8, 2],
       [9, 9, 8, 5],
       [1, 1, 4, 2]])

In [29]:
np.any((array % 7) == 0)

True

In [34]:
print(np.all(array < 11))
print(np.all(array < 9))

True
False


## Reshaping

In [35]:
array = np.arange(1,16)

In [36]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
array.reshape(3, 5) #Muda o tamanho ou muda de array para matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [42]:
array.reshape(5, 3) #Muda o tamanho ou muda de array para matriz

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Ordenando o Array

In [43]:
array = np.array([[3,2],[10,-1]])

In [44]:
array

array([[ 3,  2],
       [10, -1]])

In [62]:
# SORT(AXIS = 1) Ordena por Linhas (Horizontal) / Usa o eixo 1 = linha

array.sort(axis = 1)

In [56]:
array

array([[ 2,  3],
       [-1, 10]])

In [57]:
array = np.array([[3,2],[10,-1]])

In [58]:
array

array([[ 3,  2],
       [10, -1]])

In [63]:
# SORT(AXIS = 0) Ordena por Colunas (Vertical) / Usa o eixo 0 = coluna

array.sort(axis = 0)

In [60]:
array

array([[ 3, -1],
       [10,  2]])